version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config:/config
      - /media/cola/Data2/Music:/music
#      - <path/to/tvseries>:/data/tvshows
#      - </path/to/movies>:/data/movies
#      - </path for transcoding>:/transcode
    restart: unless-stopped
