version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
#      - PUID=1000
#      - PGID=1000
      - VERSION=docker
    volumes:
      - ./confg:/config
      - /media/cola/Data/Music:/music
#      - <path/to/tvseries>:/data/tvshows
#      - </path/to/movies>:/data/movies
#      - </path for transcoding>:/transcode
    restart: unless-stopped
