version: '3'
services:
  srv:    
    image: funkwhale/all-in-one:0.18.3
    restart: unless-stopped
    env_file: .env
    ports:
     - "80:80"
    volumes:
     - ./data:/data
     - /media/cola/Data/Music:/music:ro 